dist: xenial
language: node_js
node_js: stable
env:
 global:
   - URL_REPO: github.com/stephen-a2z/stephen-a2z.github.io.git
# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - github_pages
# 设置缓存文件
cache:
  directories:
    - node_modules
#在构建之前安装hexo环境
before_install: true

#安装git插件和搜索功能插件
install:
  - echo `pwd`
  - npm install
  - npm install hexo-deployer-git --save
  - npm install hexo-generator-searchdb --save
  - echo -e `npm list`
  # 设置git提交名，邮箱；替换真实token到_config.yml文件
before_script:
  - git config user.name "stephen-a2z"
  - git config user.email "stephen2Lingua@163.com"
  # 替换同目录下的_config.yml文件中github_token字符串为travis后台刚才配置的变量，注>意此处sed命令用了双引号。单引号无效！
  # - sed -i '' "s/github_token/${GH_ACCESS_TOKEN}/g" ./_config.yml || exit 1 # osx
  - sed -i "s/github_token/${GH_ACCESS_TOKEN}/g" ./_config.yml || exit 1
  - echo -e `hexo v`

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  # generate CNAME
  - cd public && echo 'liaoyu.online' > CNAME && cd ..
  - hexo deploy
  - hexo clean
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - stephen_a2z@foxmail.com
  on_success: change
  on_failure: always
# install: ./install-dependencies.sh
